Merge develop_lee into develop
jmtsuji/rotary pull request #214
Opened 2024-07-19 20:27 UTC by LeeBergstrand

I have merged all the current backlog of pull requests into develop_lee as they are piling up.

2024-09-30 06:57 UTC, jmtsuji requested changes
@LeeBergstrand thanks so much for making this PR and for adding a concise summary of changes. Overall, these looks like a nice set of changes for adding stability and enhancing reporting. The complete end-to-end test on my end (for one sample) passed flawlessly.

I've added a couple very minor comments in my code review that can be quickly addressed, along with a couple brief discussions point. I also reply to a few of your specific comments in the PR description below.

Really appreciate your work on this, and sorry for taking a long time to add a review. Other than the discussion points I left, this should be good to merge.

## Comments on your PR description

I am OK with most of the comments you left in your PR description, so I will just reply to a few of them below.

> In the rule search_contig_start, add the -p meta flag to run prodigal in meta mode. The prodigal doesn't scan the genome in this mode to build the gene-calling model. Instead, it predicts genes using prebuilt models, which is suitable for metagenomics. Prodigal requires at least 20K bases to make a model, which is larger than many circular plasmids. In some cases, Prodigal would fail when the only circular element is a small plasmid because the rest of the genome is fragmented and the plasmid is shorter than 20K bases. @jmtsuji Do you think running the -p meta flag should be sufficient if we are doing a start gene search?

I comment on this in the code review, but agreed -- let's change to -p to support small assemblies.

> Remove end_repair assemblies from assembly stats as they are most often identical to the flye assembly stats.

OK -- sounds reasonable. You'll see in the code review that I suggest to add the post-polishing assembly to the assembly stats because some contigs can be removed during length filtration.


> Snakemake 8.6.0 introduced a bug that prevents the deletion of temp files created before a checkpoint, causing storage issues due to accumulating gigabytes of temp files, which I reported in Temp files are not deleted for rule before checkpoint that is rerun after checkpoint with new data.  snakemake/snakemake#2982. Downgrade to version 7 to temporarily fix this issue. Details: Fix snakemake version to be less than 8.6.0 to fix temp delete issue. #216. I was originally going to go back to snakemake version 8.5.5 but I found that this version also causes some stability issues (I think it was before version 8's initial release), so I decided to downgrade to version 7. Details: Move rotary back to using snakemake 7 due to issues with snakemake 8 #217

Thanks for working on this. Too bad about snakemake 8... I guess we need to wait for now until an update is released. I'll check out the new PR you made (regarding snakemake 8) after this.

> Aggregate checkm stats from all samples into a single file for easier viewing.
> Aggregate gtdbtk reports from all samples into a single file for easier viewing.
> Change the top-level stats folder name to 'aggregate_stats' to indicate that this folder contains stats from multiple samples

This is a great addition - thanks. In addition to stats, I wonder if it would make sense to package all of the final genomes into a ZIP file or something that could accompany the summary stats -- what do you think? This could replace (or supplement) the current per-genome ZIP folder.

> Modify rule set_up_sample_directories so that each sample directory is generated dynamically and remove the sample tsv as input. This allows the sample TSV to be modified without causing the entire pipeline to be run all over again from scratch.

Cool change!


Look forward to your feedback. Thanks again.

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/assembly.smk
> +        flye_assembly = "{sample}/assembly/flye/{sample}_flye_assembly.fasta"
@LeeBergstrand During the polish phase, low coverage contigs are filtered out of the assembly. Because of this, I think it might make sense to add another input line for the post-polish genome, e.g.,

```
polish_assembly= "{sample}/polish/{sample}_polish.fasta"
```

What do you think?

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/assembly.smk
> +        flye_assembly = "{sample}/assembly/flye/{sample}_flye_assembly.fasta"
If we make this change, then this QUAST rule might work better in a different snakemake file than `assembly.smk`. For example, we might need to make a separate snakefile like `aggregate.smk`...

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/circularize.smk
> +        if len(contig_info_filtered) == 0:
Helpful addition -- thanks.

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/circularize.smk
> +        prodigal -i {input.contigs} -a {output.orf_predictions} -d {output.gene_predictions} -p meta \
Agreed, let's use `-p meta` for these rough ORF predictions.

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/qc.smk
> +        left_qc_stats='aggregate_stats/qc/before_and_after_qc_sequence_stats_short_R1.tsv',
@LeeBergstrand These aggregated summary files are very helpful -- thanks! What might you think about combining the R1 and R2 short read stats into a single file, for conciseness? Another column of R1 vs. R2 could be added to each existing file, and then the R1 and R2 files could be concatenated vertically.

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/qc.smk
> +        left_qc_stats='aggregate_stats/qc/before_and_after_qc_sequence_stats_short_R1.tsv',
This could be done in a future PR so we can go ahead and merge this PR.

2024-09-30 06:57 UTC, jmtsuji commented on rotary/rules/circularize.smk
> +        prodigal -i {input.contigs} -a {output.orf_predictions} -d {output.gene_predictions} -p meta \
We do not need to change anything for this PR, but one other idea I've played around with is using DFAST (without functional annotations, just gene calling) for this step, to ensure that the called genes during this phase are consistent with those in the final assembly. Any thoughts on this idea?

2024-10-02 01:16 UTC, LeeBergstrand commented on rotary/rules/circularize.smk
> +        prodigal -i {input.contigs} -a {output.orf_predictions} -d {output.gene_predictions} -p meta \
@jmtsuji I think using dfast for this step could work. I want to discuss with you about dfast vs prodigal in our next meeting.

2024-10-02 01:17 UTC, LeeBergstrand commented on rotary/rules/qc.smk
> +        left_qc_stats='aggregate_stats/qc/before_and_after_qc_sequence_stats_short_R1.tsv',
@jmtsuji I open to different formats. That makes sense.

2024-10-02 07:23 UTC, jmtsuji commented on rotary/rules/circularize.smk
> +        prodigal -i {input.contigs} -a {output.orf_predictions} -d {output.gene_predictions} -p meta \
@LeeBergstrand Sounds good. I'm not sure how well DFAST would perform on a highly fragmented input genome... let's discuss more later.

2024-10-02 07:23 UTC, jmtsuji commented on rotary/rules/qc.smk
> +        left_qc_stats='aggregate_stats/qc/before_and_after_qc_sequence_stats_short_R1.tsv',
OK -- I'll convert this to an issue so we can consider it later.

2024-10-02 07:26 UTC, jmtsuji commented on rotary/rules/qc.smk
> +        left_qc_stats='aggregate_stats/qc/before_and_after_qc_sequence_stats_short_R1.tsv',
Now in #222

2024-10-03 00:48 UTC, jmtsuji commented on rotary/rules/circularize.smk
> +        prodigal -i {input.contigs} -a {output.orf_predictions} -d {output.gene_predictions} -p meta \
Update: not sure that DFAST could handle annotating just a short circular plasmid properly. Let's just keep on using prodigal.

2024-10-03 01:03 UTC, jmtsuji commented on rotary/rules/assembly.smk
> +        flye_assembly = "{sample}/assembly/flye/{sample}_flye_assembly.fasta"
Converted to issue #224

2024-10-03 05:31 UTC, jmtsuji commented
@LeeBergstrand All comments are now addressed. It might make sense to first review and merge #223 into this branch before merging into develop, but otherwise, #223 could be handled as a separate PR directly into develop. So feel free to merge this PR (#214) when ready.

2024-10-03 18:34 UTC, merged